@port=3000
@host=http://localhost:{{port}}/api

# auth start
POST {{host}}/auth/captcha/login HTTP/1.1
Content-Type: application/json

{
    "phone":"13486827301"
}
###
POST {{host}}/auth/login/code HTTP/1.1
Content-Type: application/json

{
    "phone":"13486827301",
    "code":null
}
# auth end

# cate start
###
POST {{host}}/category HTTP/1.1
Content-Type: application/json

{
    "name":"News"
}
###
GET {{host}}/category/2 HTTP/1.1